mysite/homepage/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # path('site1/', include('site1.urls')),
    path('poll/', include('poll.urls')),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('site1/', include('site1.urls')),
    # path('poll/', include('poll.urls')),
    path('',include('homepage.urls')),
    path('test/',include('testform.urls')),

]

mysite/poll/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /poll/
    path('', views.index, name='index'),
    # ex: /poll/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /poll/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /poll/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('delete/',views.delete,name= 'delete'),

    path('delete/delete_Q/',views.delete2,name="delete2")
]

mysite/site1/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.test1),
]

mysite/testform/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('test1/', views.test1, name='test1'),
]

mysite/homepage/models.py
from django.db import models

# Create your models here.

mysite/poll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/site1/models.py
from django.db import models

# Create your models here.

mysite/testform/models.py
from django.db import models

# Create your models here.

mysite/homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def home(request):
    # return HttpResponse ('<h1>Hello homepage</h1>')
    index = 'index'
    context = {'homepage': index}
    return render(request, 'homepage/home.html', context)

mysite/poll/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question,Choice
from django.urls import reverse

# Create your views here.
def index(request):
    question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'question_list': question_list}
    return render(request, 'polls/index2.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice1'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def delete(request):
    question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'question_list': question_list}
    # try:
    #     selected_question = question_list.get(pk=request.POST['choice1'])
    # except (KeyError, Choice.DoesNotExist):
    #     # Redisplay the question voting form.
    #     return render(request, 'polls/delete.html', {
    #         # 'question': question,
    #         'error_message': "You didn't select a choice.",
    #     })
    # else:
    #     selected_question.delete()
    #     selected_question.save()
    return render(request, 'polls/delete.html', context)

def delete2(request):
    question = Question.objects.all()
    # selected_Q = Question.object.get(id=request.POST['question'])
    # return HttpResponse(question)
    try:
        selected_Q = Question.objects.get(id=request.POST['question'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/delete.html', {
            'question_list': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_Q.delete()

        return HttpResponseRedirect(reverse('polls:index'))

mysite/site1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

# Create your views here.
def test1(request):
    var_string = 'Hello,Django'
    var2_list = ['web1','web2','web3']
    temp = loader.get_template('index.html')
    context ={
        'var1': var_string,
        'var2': var2_list
    }
    return HttpResponse(temp.render(context,request))

mysite/testform/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.

def test1(request):
    return render(request,'testform/test1.html')

mysite/homepage/templates/homepage/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<h1>welcome homepage</h1>
    <ul>
        <li><a href="/poll">{{ homepage }}</a></li>
    </ul>
</body>
</html>

mysite/poll/templates/polls/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:delete2' %}" method="post">
    {% csrf_token %}
{% for Q in question_list %}
    <input type="radio" name="question" id="Q{{ forloop.counter }}" value="{{ Q.id }}">
    <label for="Q{{ forloop.counter }}">{{ Q.question_text }}</label><br>
{% endfor %}
<hr>
<input type="submit" value="delete">

</form>
</body>
</html>

mysite/poll/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice1" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</body>
</html>

mysite/poll/templates/polls/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    {% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'polls:detail' question.id %}"><h1>{{ question.question_text }}</h1></a></li>
    {% endfor %}
    </ul>
    <ul><li><a href="{% url 'polls:delete' %}">delete question</a></li></ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

mysite/poll/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

mysite/site1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <BODY BGCOLOR="81dbc6" >
    <h1>{{var1}}</h1>
    {% for i in var2 %}
        <h2>{{ i }}</h2>
        {% if i == "web2" %}
        <hr/>
            <h3>hello web2</h3>
        <hr/>
        {% endif %}
    {% endfor %}
</body>
</html>

mysite/testform/templates/testform/test1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<h1>Text</h1>
<input type="text" name="txt_user" id="1" value="default value" size="20" maxlength="30"/><br>
<input type="text" name="txt_user" value="default value" size="40" maxlength="30" disabled="disabled" /><br>
<input type="text" name="txt_user1" value="readonly" size="20" maxlength="30" readonly="readonly" />
<hr>

<h1>Checkbox</h1>
<input type="checkbox" name="selection1" value="Yes" checked="checked" /> Selection 1
<input type="checkbox" name="selection2" value="Yes" /> Selection 2
<input type="checkbox" name="selection3" value="Yes" /> Selection 3
<hr>

<h1>Radio</h1>
<input type="radio" name="sex" value="M" checked="checked" /> Male <br>
<input type="radio" name="sex" value="F" /> Female
<hr>

<h1>Password</h1>
<input type="password" name="txt_passw" value="" size="10" maxlength="30" />
<hr>

<h1>File</h1>
    <input type="file" name="fileToUpload" id="fileToUpload">
<hr>

<h1>Hidden</h1>
<input type="hidden" name="id" value="1234" />
<hr>

<h1>Button</h1>
<input type="button" name="ok" value="OK" >
<hr>

<h1>Submit</h1>
<input type="submit" name="save" value="Save" />
<hr>

<h1>Reset</h1>
<form action="">
<input type="password" name="txt_passw" value="" size="10" maxlength="30" />
<input type="reset" name="Clear">
</form>
<hr>

<h1>Select</h1>
<select name="list" size="4" multiple>
<option value="1">option 1</option>
<option value="2">option 2</option>
<option value="3"selected="selected">option 3</option>
<option value="4">option 4</option>
<option value="5">option 5</option>
</select>
<hr>


้<h1>Textarea</h1>
<textarea name="comment" rows="20" cols="60">
________´$$$$`_____________________________,,,_
_______´$$$$$$$`_________________________´$$$`
________`$$$$$$$`______,,________,,_______´$$$$´
_________`$$$$$$$`____´$$`_____´$$`____´$$$$$´
__________`$$$$$$$`_´$$$$$`_´$$$$$`__´$$$$$$$´
___________`$$$$$$$_$$$$$$$_$$$$$$$_´$$$$$$$´_
____________`$$$$$$_$$$$$$$_$$$$$$$`´$$$$$$´_
___,,,,,,______`$$$$$$_$$$$$$$_$$$$$$$_$$$$$$´_
_´$$$$$`____`$$$$$$_$$$$$$$_$$$$$$$_$$$$$$´_
´$$$$$$$$$`´$$$$$$$_$$$$$$$_$$$$$$$_$$$$$´_
´$$$$$$$$$$$$$$$$$$_$$$$$$$_$$$$$$$_$$$$$´_
___`$$$$$$$$$$$$$$$_$$$$$$$_$$$$$$_$$$$$$´_
______`$$$$$$$$$$$$$_$$$$$__$$_$$$$$$_$$´_
_______`$$$$$$$$$$$$,___,$$$$,_____,$$$$$´_
_________`$$$$$$$$$$$$$$$$$$$$$$$$$$$$$´_
__________`$$$$$$$$$$$$$$$$$$$$$$$$$$$´_
____________`$$$$$$$$$$$$$$$$$$$$$$$$´_
_______________`$$$$$$$$$$$$$$$$$$$$´ _

</textarea>


</body>
</html>